# Generated by Django 5.1.7 on 2025-03-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FilePathField(path='/mnt/7C6CC15D6CC112B6/music/touhou/')),
            ],
        ),
    ]
