# Generated by Django 5.1.7 on 2025-03-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0002_rename_filename_rawfiles_raw_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfiles',
            name='raw_artist',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rawfiles',
            name='raw_tracktitle',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
