# Generated by Django 5.1.7 on 2025-03-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0003_rawfiles_raw_artist_rawfiles_raw_tracktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfiles',
            name='raw_year',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
