# Generated by Django 5.1.7 on 2025-03-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0004_rawfiles_raw_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawfiles',
            name='raw_year',
        ),
    ]
