# Generated by Django 5.1.7 on 2025-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0006_rawfiles_failed_metadata_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfiles',
            name='detected_cue_file',
            field=models.BooleanField(default=False),
        ),
    ]
