# Generated by Django 4.2.7 on 2023-11-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistsongrole',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistsongrole',
            name='role',
        ),
        migrations.AddField(
            model_name='artistsongrole',
            name='artistalbumrole',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='archive.artistalbumrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circle',
            name='defaultnamelanguage',
            field=models.CharField(choices=[('ENG', 'English'), ('JP', 'Japanese')], default='JP', max_length=100),
        ),
    ]
