# Generated by Django 4.2.7 on 2023-11-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_remove_artistsongrole_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='defaultnamelanguage',
            field=models.CharField(max_length=100),
        ),
    ]
