# Generated by Django 4.2.7 on 2023-11-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_artist_defaultnamelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='defaultnamelanguage',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='musicFile',
            field=models.FilePathField(),
        ),
    ]
